services:
  lpdg-ml:
    build: .
    volumes:
      - ./data:/app/data:ro
      - ./outputs:/app/outputs
    command: >
      sh -c "
      python src/final_predict.py
      &&
      cp /app/predictions.csv /app/outputs/predictions.csv
      &&
      python validate_submission.py
      /app/outputs/predictions.csv
      "